config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get '/best_selling', to: 'drugs#best_selling'

  root 'products#index'
  resources :customers, only: [:new, :create]
  resources :feedbacks, only: [:create]
 # config/routes.rb

resources :orders, only: [:index, :new, :create, :show] do
  member do
    get :review
  end
end


  namespace :admin do
    resources :orders, only: [:new, :create, :index]
    get '/review_order/:id', to: 'orders#review', as: 'review_order'
  end

  resources :products, only: [:index, :show] do
    collection do
      get :on_sale
      get :new_products
      get :recently_updated
    end
  end

  resource :cart, only: [:show] do
    post 'add/:id', to: 'carts#add', as: 'add'
    post 'increase/:id', to: 'carts#increase', as: 'increase'
    post 'decrease/:id', to: 'carts#decrease', as: 'decrease'
    post 'remove/:id', to: 'carts#remove', as: 'remove'
  end

  resources :categories, only: [:index, :show] do
    collection do
      get :otc
      get :prescription
      get :branded
      get :generic
    end
  end
end

app/models/about.rb
class About < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["title", "description", "content"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :encrypted_password, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name", "description"] + super
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :address, presence: true
  validates :phone_number, presence: true
  def self.ransackable_attributes(auth_object = nil)
    ["name", "email", "address", "phone_number"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders, inverse_of: :customer
  validates :name, :address, :email, :province_id, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[address created_at email id name province_id updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[orders province]
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord

    def self.ransackable_attributes(auth_object = nil)
        %w(name email content created_at updated_at) # Adjust this array according to your model's attributes
      end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, inverse_of: :orders, autosave: true
  has_many :order_items
  has_many :products, through: :order_items
  belongs_to :user, optional: true

  accepts_nested_attributes_for :customer

  validates :total, :status, :gst, :pst, :hst, :subtotal, presence: true
  validates :total, :gst, :pst, :hst, :subtotal, numericality: true

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at customer_id gst hst id pst status subtotal total updated_at]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :product_id, :quantity, :price, presence: true
  validates :quantity, numericality: { only_integer: true }
  validates :price, numericality: true

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at id order_id price product_id quantity updated_at]
  end
end

app/models/page.rb
class Page < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at"]
  end

  validates :title, :content, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  mount_uploader :image, ImageUploader
  has_many :orders
  belongs_to :supplier

  validates :name, :description, :image, :category_id, :price, :uom, :supplier_id, presence: true
  validates :category_id, :supplier_id, numericality: { only_integer: true }
  validates :price, numericality: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "image", "mat_id", "name", "price",
     "supplier_id", "uom", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[category supplier orders]
  end

  def self.ransackable_attributes(auth_object = nil)
    super + ["on_sale"]
  end
end

app/models/province.rb
# app/models/province.rb
class Province < ApplicationRecord
  has_many :tax_rates
  has_many :users

  validates :name, presence: true


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["tax_rates"]
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  validates :name, :address, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/models/tax_rate.rb
# app/models/tax_rate.rb
class TaxRate < ApplicationRecord
  belongs_to :province

  validates :province_id, :gst_rate, :pst_rate, :hst_rate, presence: true
  validates :province_id, numericality: { only_integer: true }
  validates :gst_rate, :pst_rate, :hst_rate, numericality: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst_rate", "hst_rate", "id", "province_id", "pst_rate", "updated_at"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
  validates :email, presence: true, uniqueness: true,
format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :encrypted_password, :address, :province_id, :name, presence: true
  validates :province_id, numericality: { only_integer: true }


  has_many :orders

  def self.ransackable_attributes(auth_object = nil)
    %w[id name address email province_id created_at updated_at]
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Medicine</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>


  <body>
    <%= render 'shared/header' %>

    <div class="container">
      <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<% if user_signed_in? %>
  <p>Welcome, <%= current_user.email %>!</p>
<% end %>


      <%= yield %>

      <!-- Include Bootstrap JavaScript (optional) -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About Us</h1>
  <h2><%= @about.title %></h2>

  <% @about.content.split("\n").each do |paragraph| %>
    <p><%= paragraph %></p>
  <% end %>
</div>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Name: <%= @contact.name %></p>
<p>Email: <%= @contact.email %></p>
<p>Address: <%= @contact.address %></p>
<p>Phone Number: <%= @contact.phone_number %></p>

app/views/shared/_breadcrumbs.html.erb
<% if @breadcrumbs %>
  <nav class="breadcrumbs">
    <% @breadcrumbs.each_with_index do |breadcrumb, index| %>
      <% if breadcrumb[:url].present? && index < @breadcrumbs.length - 1 %>
        <%= link_to breadcrumb[:name], breadcrumb[:url] %> &gt;
      <% else %>
        <%= breadcrumb[:name] %>
      <% end %>
    <% end %>
  </nav>
<% end %>

app/views/shared/_header.html.erb
<!-- app/views/shared/_header.html.erb -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "psalms.png", alt: "Logo", class: "logo-img" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Best Selling Drugs', best_selling_path, class: "nav-link text-light" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Orders", orders_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link text-light" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
          </li>
        <% end %>
      </ul>

      <!-- View Cart and Item Count -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'View Cart', cart_path, class: "nav-link text-light" %>
          <% if session[:cart] && session[:cart].values.sum > 0 %>
            <span class="ml-2 text-light">(<%= session[:cart].values.sum %> items)</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>