config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get '/best_selling', to: 'drugs#best_selling'

  root 'products#index'
  resources :customers, only: [:new, :create]
  resources :feedbacks, only: [:create]
 # config/routes.rb

resources :orders, only: [:index, :new, :create, :show] do
  member do
    get :review
  end
end


  namespace :admin do
    resources :orders, only: [:new, :create, :index]
    get '/review_order/:id', to: 'orders#review', as: 'review_order'
  end

  resources :products, only: [:index, :show] do
    collection do
      get :on_sale
      get :new_products
      get :recently_updated
    end
  end

  resource :cart, only: [:show] do
    post 'add/:id', to: 'carts#add', as: 'add'
    post 'increase/:id', to: 'carts#increase', as: 'increase'
    post 'decrease/:id', to: 'carts#decrease', as: 'decrease'
    post 'remove/:id', to: 'carts#remove', as: 'remove'
  end

  resources :categories, only: [:index, :show] do
    collection do
      get :otc
      get :prescription
      get :branded
      get :generic
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name", "description"] + super
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/controllers/categories_controller.rb
# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show otc prescription branded generic]
  before_action :add_common_breadcrumbs

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def show
    add_breadcrumb @category.name, category_path(@category)
    @products = @category.products.page(params[:page]).per(10)
  end

  def otc
    otc_category("OTC")
  end

  def prescription
    otc_category("Prescription")
  end

  def branded
    otc_category("Branded")
  end

  def generic
    otc_category("Generic")
  end

  private

  def set_category
    @category = Category.find_by(name: params[:id])
  end

  def otc_category(name)
    @category = Category.find_or_create_by(name: name)
    add_breadcrumb @category.name, category_path(@category)
    @products = @category.products.page(params[:page]).per(10)
    render "show"
  end

  def add_common_breadcrumbs
    add_breadcrumb "Home", root_path
    add_breadcrumb "Categories", categories_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_products_table.html.erb
<%= render 'shared/breadcrumbs' %>

<% if products.present? %>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% products.each do |product| %>
          <tr>
            <td>
              <% if product.image.present? %>
                <%= image_tag product.image.url, alt: product.name, class: "img-thumbnail", style: "max-width: 100px; max-height: 100px;" %>
              <% else %>
                <p>Image Not Available</p>
              <% end %>
            </td>
            <td><%= link_to product.name, product_path(product) %></td>
            <td><%= number_to_currency(product.price) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>No products found for <%= @category.capitalize %>.</p>
<% end %>

app/views/categories/branded.html.erb
<%= render 'shared/breadcrumbs' %>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <h1>Branded Products</h1>
       <%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>
      <%= render 'products_table', products: @products %>
     
    </div>
  </div>
</div>

app/views/categories/generic.html.erb
<%= render 'shared/breadcrumbs' %>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <h1>Generic Products</h1>
      <%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>
      <%= render 'products_table', products: @products %>
      
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<%= render 'shared/breadcrumbs' %>

<div class="container mt-4">
  <h1>Categories</h1>

  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "OTC", otc_categories_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Prescription", prescription_categories_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Branded", branded_categories_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Generic", generic_categories_path, class: "nav-link" %>
    </li>
  </ul>

  <h2>Products</h2>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td>
            <% if product.image.present? %>
              <%= image_tag product.image.url, alt: product.name, class: "img-thumbnail" %>
            <% else %>
              <p>Image Not Available</p>
            <% end %>
          </td>
          <td><%= link_to product.name, product_path(product) %></td>
          <td><%= number_to_currency(product.price) %></td>
          <td><%= product.category.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Pagination -->
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      <% if @products.total_pages > 1 %>
        <% min_page = [@products.current_page - 4, 1].max %>
        <% max_page = [min_page + 9, @products.total_pages].min %>
        <% (min_page..max_page).each do |page| %>
          <% if @products.current_page == page %>
            <li class="page-item active">
              <span class="page-link"><%= page %><span class="sr-only">(current)</span></span>
            </li>
          <% else %>
            <li class="page-item">
              <%= link_to page, { page: page }, class: 'page-link' %>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </nav>
</div>

app/views/categories/otc.html.erb
<!-- app/views/categories/otc.html.erb -->
<%= render 'shared/breadcrumbs' %>

<h1>OTC Products</h1>
<%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>
<%= render 'products_table', products: @products %>

app/views/categories/prescription.html.erb
<!-- app/views/categories/prescription.html.erb -->
<%= render 'shared/breadcrumbs' %>

<h1>Prescription Products</h1>
<%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary mt-3' %>
<%= render 'products_table', products: @products %>


app/views/categories/show.html.erb
<%= render 'shared/breadcrumbs' %>

<div class="container">
  <h1><%= @category.name %> Products</h1>
  <%= link_to "Back to Categories", categories_path %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Category</th>
        <th>Image</th>
        <th>Name</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= @category.name %></td>
          <td>
            <% if product.image.present? %>
              <%= image_tag product.image.url, alt: product.name, class: "img-thumbnail" %>
            <% else %>
              <p>Image Not Available</p>
            <% end %>
          </td>
          <td><%= link_to product.name, product_path(product) %></td>
          <td><%= number_to_currency(product.price) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Pagination -->
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      <% if @products.total_pages > 1 %>
        <% min_page = [@products.current_page - 4, 1].max %>
        <% max_page = [min_page + 9, @products.total_pages].min %>
        <% (min_page..max_page).each do |page| %>
          <% if @products.current_page == page %>
            <li class="page-item active">
              <span class="page-link"><%= page %><span class="sr-only">(current)</span></span>
            </li>
          <% else %>
            <li class="page-item">
              <%= link_to page, { page: page }, class: 'page-link' %>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </nav>
</div>